### ISSUE TITLE
Better stack traces, avoid sending plane 500 codes

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1247]
If you have access, check out [this log entry](https://pantheon.corp.google.com/logs/viewer?project=dartlang-pub&minLogLevel=0&expandAll=false&timestamp=2018-04-27T22:40:22.001000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeEnd=2018-04-27T22:40:22.001Z&interval=PT1H&resource=gae_app%2Fmodule_id%2Fdefault&scrollTimestamp=2018-04-27T21:19:11.107000000Z&logName=projects%2Fdartlang-pub%2Flogs%2Fappengine.googleapis.com%252Fstdout&logName=projects%2Fdartlang-pub%2Flogs%2Fappengine.googleapis.com%252Fstderr&logName=projects%2Fdartlang-pub%2Flogs%2Fappengine.googleapis.com%252Fnginx.request&logName=projects%2Fdartlang-pub%2Flogs%2Fappengine.googleapis.com%252Frequest_log&dateRangeUnbound=backwardInTime&advancedFilter=resource.type%3D%22gae_app%22%0Aresource.labels.zone%3D%22us-central1-b%22%0Aresource.labels.project_id%3D%22dartlang-pub%22%0Aresource.labels.version_id%3D%2220180409t142629%22%0Aresource.labels.module_id%3D%22default%22%0Atimestamp%3D%222018-04-27T21:19:11.107000000Z%22%0AinsertId%3D%221t7d774f54f0s6%22).

```
Error:
    GrpcProtocolException: No trailing headers from server.

Stack:
    #0      Client.invoke (package:appengine/src/grpc_api_impl/grpc.dart:199:9)
    <asynchronous suspension>
    #1      Channel.invoke (package:appengine/src/grpc_api_impl/grpc.dart:45:19)
    <asynchronous suspension>
    #2      DatastoreApi.runQuery (package:appengine/src/grpc_api/dart/google/datastore/v1/datastore.pb.dart:580:20)
    #3      GrpcDatastoreImpl.query (package:appengine/src/grpc_api_impl/datastore_impl.dart:252:32)
    <asynchronous suspension>
    #4      Query.run.<anonymous closure> (package:gcloud/src/db/db.dart:238:12)
    #5      StreamFromPages._onListen (package:gcloud/common.dart:72:23)
    #6      _runGuarded (dart:async/stream_controller.dart:804)
    #7      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:683)
    #8      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:408)
    #9      _StreamController._subscribe (dart:async/stream_controller.dart:682)
    #10     _ControllerStream._createSubscription (dart:async/stream_controller.dart:817)
    #11     _StreamImpl.listen (dart:async/stream_impl.dart:466)
    #12     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:123)
    #13     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:91)
    #14     _ForwardingStream.listen (dart:async/stream_pipe.dart:86)
    #15     GCloudPackageRepository.versions.<anonymous closure> (package:pub_dartlang_org/frontend/backend.dart:182:62)
    #16     _runGuarded (dart:async/stream_controller.dart:804)
    #17     _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:683)
    #18     _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:408)
    #19     _StreamController._subscribe (dart:async/stream_controller.dart:682)
    #20     _ControllerStream._createSubscription (dart:async/stream_controller.dart:817)
    #21     _StreamImpl.listen (dart:async/stream_impl.dart:466)
    #22     Stream.toList (dart:async/stream.dart:968)
    #23     ShelfPubServer._listVersions (package:pub_server/shelf_pubserver.dart:244:62)
    <asynchronous suspension>
    #24     ShelfPubServer.requestHandler (package:pub_server/shelf_pubserver.dart:164:16)
    <asynchronous suspension>
    #25     appHandler (package:pub_dartlang_org/frontend/handlers.dart:82:23)
    <asynchronous suspension>
    #26     main.<anonymous closure>.<anonymous closure> (file:///project/app/bin/service/frontend.dart:43:36)
    #27     _userAuthParsingWrapper.<anonymous closure> (package:pub_dartlang_org/shared/handler_helpers.dart:83:19)
    <asynchronous suspension>
    #28     _sanitizeRequestWrapper.<anonymous closure> (package:pub_dartlang_org/shared/handler_helpers.dart:76:19)
    <asynchronous suspension>
    #29     redirectToHttpsWrapper.<anonymous closure> (package:pub_dartlang_org/shared/handler_helpers.dart:94:21)
    <asynchronous suspension>
    #30     _logRequestWrapper.<anonymous closure> (package:pub_dartlang_org/shared/handler_helpers.dart:42:27)
    <asynchronous suspension>
    #31     handleRequest (package:shelf/shelf_io.dart:88:29)
    <asynchronous suspension>
    #32     handleRequest (package:pub_dartlang_org/shared/handler_helpers.dart:36:5)
    #33     runHandler.<anonymous closure> (package:pub_dartlang_org/shared/handler_helpers.dart:31:48)
    #34     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:65:12)
    #35     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:60:16)
    #36     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:208:19)
    #37     _rootRun (dart:async/zone.dart:1126)
    #38     _CustomZone.run (dart:async/zone.dart:1023)
    #39     runZoned (dart:async/zone.dart:1490)
    #40     _ServiceScope._fork (package:gcloud/service_scope.dart:207:12)
    #41     fork (package:gcloud/service_scope.dart:103:30)
    #42     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:58:7)
    #43     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:78:16)
    #44     _rootRunUnary (dart:async/zone.dart:1134)
    #45     _CustomZone.runUnary (dart:async/zone.dart:1031)
    #46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
    #47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    #48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    #49     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
    #50     _StreamController._add (dart:async/stream_controller.dart:639)
    #51     _StreamController.add (dart:async/stream_controller.dart:585)
    #52     _HttpServer._handleRequest (dart:_http/http_impl.dart:2636)
    #53     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2393)
    #54     _rootRunUnary (dart:async/zone.dart:1134)
    #55     _CustomZone.runUnary (dart:async/zone.dart:1031)
    #56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
    #57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    #58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    #59     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
    #60     _StreamController._add (dart:async/stream_controller.dart:639)
    #61     _StreamController.add (dart:async/stream_controller.dart:585)
    #62     _HttpParser._headersEnd (dart:_http/http_parser.dart:372)
    #63     _HttpParser._doParse (dart:_http/http_parser.dart:701)
    #64     _HttpParser._parse (dart:_http/http_parser.dart:318)
    #65     _HttpParser._onData (dart:_http/http_parser.dart:810)
    #66     _rootRunUnary (dart:async/zone.dart:1134)
    #67     _CustomZone.runUnary (dart:async/zone.dart:1031)
    #68     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
    #69     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    #70     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    #71     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
    #72     _StreamController._add (dart:async/stream_controller.dart:639)
    #73     _StreamController.add (dart:async/stream_controller.dart:585)
    #74     _Socket._onData (dart:io-patch/socket_patch.dart:1674)
    #75     _rootRunUnary (dart:async/zone.dart:1138)
    #76     _CustomZone.runUnary (dart:async/zone.dart:1031)
    #77     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
    #78     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    #79     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    #80     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
    #81     _StreamController._add (dart:async/stream_controller.dart:639)
    #82     _StreamController.add (dart:async/stream_controller.dart:585)
    #83     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
    #84     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:799)
    #85     _microtaskLoop (dart:async/schedule_microtask.dart:41)
    #86     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
    #87     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
    #88     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

**Comment by kevmoo** [comment]
Consider this

```diff
diff --git a/app/lib/shared/handler_helpers.dart b/app/lib/shared/handler_helpers.dart
index e0b2b47..664575d 100644
--- a/app/lib/shared/handler_helpers.dart
+++ b/app/lib/shared/handler_helpers.dart
@@ -10,6 +10,7 @@ import 'package:logging/logging.dart';
 import 'package:path/path.dart' as path;
 import 'package:shelf/shelf.dart' as shelf;
 import 'package:shelf/shelf_io.dart' as shelf_io;
+import 'package:stack_trace/stack_trace.dart';
 
 import '../frontend/service_utils.dart';
 import '../frontend/templates.dart';
@@ -41,7 +42,7 @@ shelf.Handler _logRequestWrapper(Logger logger, shelf.Handler handler) {
     try {
       return await handler(request);
     } catch (error, st) {
-      logger.severe('Request handler failed', error, st);
+      logger.severe('Request handler failed', error, new Trace.from(st));
 
       final title = 'Pub is not feeling well';
       Map<String, String> debugHeaders;
diff --git a/app/pubspec.yaml b/app/pubspec.yaml
index eff95e2..a7731ce 100644
--- a/app/pubspec.yaml
+++ b/app/pubspec.yaml
@@ -28,6 +28,7 @@ dependencies:
   pub_semver: ">=1.2.2 <2.0.0"
   pub_server: ">=0.1.0 <0.2.0"
   shelf: '>=0.5.6 <0.8.0'
+  stack_trace: ^1.1.4
   stream_transform: ^0.0.7
   yaml: '^2.1.12'
   # pana version to be pinned
```

I think this will give a much cleaner stack in the log – but I couldn't get the server to run locally to verify
