### ISSUE TITLE
Investigate: can Flutter be in a lock?

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#1390]
````
Error: FormatException: Unexpected character (at character 1) Waiting for another flutter command to release the startup lock... ^
Stack:
#0 _ChunkedJsonParser.fail (dart:convert-patch/dart:convert/convert_patch.dart:1374)
#1 _ChunkedJsonParser.parseNumber (dart:convert-patch/dart:convert/convert_patch.dart:1270)
#2 _ChunkedJsonParser.parse (dart:convert-patch/dart:convert/convert_patch.dart:938)
#3 _parseJson (dart:convert-patch/dart:convert/convert_patch.dart:29)
#4 JsonDecoder.convert (dart:convert/json.dart:542)
#5 JsonCodec.decode (dart:convert/json.dart:169)
#6 ToolEnvironment.getFlutterVersion 
````

**Comment by zoechi** [comment]
`flutter packages pub run build_runner watch` caused this often in the past but I think this was fixed a few weeks ago.

**Comment by isoos** [comment]
Apparently it is affecting `flutter 0.5.4`, because once I reduced the concurrent processing to 1, the exception disappeared in the staging environment, and that's just a 9 days old release.
