### ISSUE TITLE
Error: pub.name_tracker: GrpcError: "Missing or insufficient permissions."

### ISSUE THREAD

**Issue by koudle** [dart-lang/pub-dartlang-dart#1788]
### Steps to Reproduce
1. Running locally without Docker
`GAE_SERVICE="default" dart bin/server.dart`
2. visit `localhost:8080`

There is an error log：
```
2018-11-16 01:14:12.762455 Info: pub.package_graph: Scanning existing package graph
2018-11-16 01:14:13.652589 Error: pub.name_tracker: GrpcError: "Missing or insufficient permissions." (code: 7)

Error:
    #0      Client.invoke (package:appengine/src/grpc_api_impl/grpc.dart:221:9)
    <asynchronous suspension>
    #1      Channel.invoke (package:appengine/src/grpc_api_impl/grpc.dart:45:19)
    <asynchronous suspension>
    #2      DatastoreApi.runQuery (package:appengine/src/grpc_api/dart/google/datastore/v1/datastore.pb.dart:741:20)
    #3      GrpcDatastoreImpl.query (package:appengine/src/grpc_api_impl/datastore_impl.dart:252:32)
    <asynchronous suspension>
    #4      Query.run.<anonymous closure> (file:///Users/kk/.pub-cache/hosted/pub.dartlang.org/gcloud-0.6.0+1/lib/src/db/db.dart:239:12)
    #5      StreamFromPages._onListen (package:gcloud/common.dart:72:5)
    #6      _runGuarded (dart:async/stream_controller.dart:804:24)
    #7      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:683:7)
    #8      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:414:13)
    #9      _StreamController._subscribe (dart:async/stream_controller.dart:682:18)
    #10     _ControllerStream._createSubscription (dart:async/stream_controller.dart:817:19)
    #11     _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
    #12     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:123:10)
    #13     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:91:16)
    #14     _ForwardingStream.listen (dart:async/stream_pipe.dart:86:12)
    #15     _StreamIterator._initializeOrDone (dart:async/stream_impl.dart:1005:30)
    #16     _StreamIterator.moveNext (dart:async/stream_impl.dart:992:12)
    #17     NameTrackerUpdater._scan (package:pub_dartlang_org/frontend/name_tracker.dart)
    <asynchronous suspension>
    #18     NameTrackerUpdater.startNameTrackerUpdates (package:pub_dartlang_org/frontend/name_tracker.dart:73:15)
    <asynchronous suspension>
    #19     setupServices (file:///Users/kk/github/pub-dartlang-dart/app/bin/service/frontend.dart:97:40)
    <asynchronous suspension>
    #20     _main.<anonymous closure> (file:///Users/kk/github/pub-dartlang-dart/app/bin/service/frontend.dart:58:44)
    <asynchronous suspension>
    #21     withAppEngineServices.<anonymous closure> (package:appengine/src/appengine_internal.dart:46:51)
    #22     _withAppEngineServicesInternal.<anonymous closure> (package:appengine/src/appengine_internal.dart:115:20)
    <asynchronous suspension>
    #23     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:210:19)
    #24     _rootRun (dart:async/zone.dart:1124:13)
    #25     _CustomZone.run (dart:async/zone.dart:1021:19)
    #26     _runZoned (dart:async/zone.dart:1516:10)
    #27     runZoned (dart:async/zone.dart:1463:12)
    #28     _ServiceScope._fork (package:gcloud/service_scope.dart:209:12)
    #29     fork (package:gcloud/service_scope.dart:104:30)
    #30     _withAppEngineServicesInternal (package:appengine/src/appengine_internal.dart:105:10)
    #31     withAppEngineServices (package:appengine/src/appengine_internal.dart:46:5)
    #32     withAppEngineServices (package:appengine/appengine.dart:108:10)
    #33     _main (file:///Users/kk/github/pub-dartlang-dart/app/bin/service/frontend.dart:57:9)
    <asynchronous suspension>
    #34     _wrapper.<anonymous closure> (package:pub_dartlang_org/shared/service_utils.dart:225:22)
    <asynchronous suspension>
    #35     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:101:24)
    #36     _rootRun (dart:async/zone.dart:1124:13)
    #37     _CustomZone.run (dart:async/zone.dart:1021:19)
    #38     _runZoned (dart:async/zone.dart:1516:10)
    #39     runZoned (dart:async/zone.dart:1463:12)
    #40     Chain.capture (package:stack_trace/src/chain.dart:99:12)
    #41     _wrapper (package:pub_dartlang_org/shared/service_utils.dart:223:9)
    #42     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:292:17)
    #43     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by isoos** [comment]
This part of the process scans for items in the Datastore. Do you have permissions for that?

**Comment by koudle** [comment]
I add the `Cloud Datastore Owner` add it works! Thanks!
