### ISSUE TITLE
Error while decoding entity (type 'List<Object>' is not a subtype of type 'List<String>' of 'value'

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#1801]
It is likely that this have started with the SDK upgrade. Maybe I shall roll it back before we figure out what else can be broken? /cc @jonasfj 

```
2018-11-20 16:10:01.926002 Error: pub.name_tracker: Bad state: Error while decoding entity (type 'List<Object>' is not a subtype of type 'List<String>' of 'value', #0      _TypeError._throwNew (dart:core/runtime/liberrors_patch.dart:89:75)
#1      _LocalInstanceMirror._invokeSetter (dart:mirrors/runtime/libmirrors_impl.dart:332:43)
#2      _LocalInstanceMirror.setField (dart:mirrors/runtime/libmirrors_impl.dart:300:5)
#3      _ModelDescription._decodeProperty (file:///Users/isoos/.pub-cache/hosted/pub.dartlang.org/gcloud-0.6.0+1/lib/src/db/model_db_impl.dart:446:12)
#4      _ModelDescription.decodeEntity.<anonymous closure> (file:///Users/isoos/.pub-cache/hosted/pub.dartlang.org/gcloud-0.6.0+1/lib/src/db/model_db_impl.dart:428:7)
#5      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#6      _ModelDescription.decodeEntity (file:///Users/isoos/.pub-cache/hosted/pub.dartlang.org/gcloud-0.6.0+1/lib/src/db/model_db_impl.dart:427:34)
#7      _ExpandoModelDescription.decodeEntity (file:///Users/isoos/.pub-cache/hosted/pub.dartlang.org/gcloud-0.6.0+1/lib/src/db/model_db_impl.dart:510:32)
#8      ModelDBImpl.fromDatastoreEntity (file:///Users/isoos/.pub-cache/hosted/pub.dartlang.org/gcloud-0.6.0+1/lib/src/db/model_db_impl.dart:128:31)
#9      _MapStream._handleData (dart:async/stream_pipe.dart:227:21)
#10     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#11     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#12     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#13     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#20     _StreamController._add (dart:async/stream_controller.dart:640:7)
#21     _StreamController.add (dart:async/stream_controller.dart:586:5)
#22     List.forEach (dart:core/runtime/libgrowable_array.dart:277:8)
#23     StreamFromPages._handlePage (package:gcloud/common.dart:61:16)
#24     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#25     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#26     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
#27     _rootRunUnary (dart:async/zone.dart:1132:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#29     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#31     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#32     Future._complete (dart:async/future_impl.dart:473:7)
#33     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#34     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#35     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#36     GrpcDatastoreImpl.query (package:appengine/src/grpc_api_impl/datastore_impl.dart)
<asynchronous suspension>
#37     Query.run.<anonymous closure> (file:///Users/isoos/.pub-cache/hosted/pub.dartlang.org/gcloud-0.6.0+1/lib/src/db/db.dart:239:12)
#38     StreamFromPages._onListen (package:gcloud/common.dart:72:5)
#39     _runGuarded (dart:async/stream_controller.dart:805:24)
#40     _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:684:7)
#41     _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:414:13)
#42     _StreamController._subscribe (dart:async/stream_controller.dart:683:18)
#43     _ControllerStream._createSubscription (dart:async/stream_controller.dart:818:19)
#44     _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
#45     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:123:10)
#46     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:91:16)
#47     _ForwardingStream.listen (dart:async/stream_pipe.dart:86:12)
#48     _StreamIterator._initializeOrDone (dart:async/stream_impl.dart:1003:30)
#49     _StreamIterator.moveNext (dart:async/stream_impl.dart:990:12)
#50     NameTrackerUpdater._scan (package:pub_dartlang_org/frontend/name_tracker.dart)
<asynchronous suspension>
#51     NameTrackerUpdater.startNameTrackerUpdates (package:pub_dartlang_org/frontend/name_tracker.dart:73:15)
<asynchronous suspension>
#52     setupServices (file:///Users/isoos/work/google/pub/pub-dartlang-dart/app/bin/service/frontend.dart:97:40)
<asynchronous suspension>
#53     _main.<anonymous closure> (file:///Users/isoos/work/google/pub/pub-dartlang-dart/app/bin/service/frontend.dart:58:44)
<asynchronous suspension>
#54     withAppEngineServices.<anonymous closure> (package:appengine/src/appengine_internal.dart:46:51)
#55     _withAppEngineServicesInternal.<anonymous closure> (package:appengine/src/appengine_internal.dart:115:20)
<asynchronous suspension>
#56     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:210:19)
#57     _rootRun (dart:async/zone.dart:1124:13)
#58     _CustomZone.run (dart:async/zone.dart:1021:19)
#59     _runZoned (dart:async/zone.dart:1516:10)
#60     runZoned (dart:async/zone.dart:1463:12)
#61     _ServiceScope._fork (package:gcloud/service_scope.dart:209:12)
#62     fork (package:gcloud/service_scope.dart:104:30)
#63     _withAppEngineServicesInternal (package:appengine/src/appengine_internal.dart:105:10)
#64     withAppEngineServices (package:appengine/src/appengine_internal.dart:46:5)
#65     withAppEngineServices (package:appengine/appengine.dart:108:10)
#66     _main (file:///Users/isoos/work/google/pub/pub-dartlang-dart/app/bin/service/frontend.dart:57:9)
<asynchronous suspension>
#67     _wrapper.<anonymous closure> (package:pub_dartlang_org/shared/service_utils.dart:225:22)
<asynchronous suspension>
#68     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:101:24)
#69     _rootRun (dart:async/zone.dart:1124:13)
#70     _CustomZone.run (dart:async/zone.dart:1021:19)
#71     _runZoned (dart:async/zone.dart:1516:10)
#72     runZoned (dart:async/zone.dart:1463:12)
#73     Chain.capture (package:stack_trace/src/chain.dart:99:12)
#74     _wrapper (package:pub_dartlang_org/shared/service_utils.dart:223:9)
#75     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:292:17)
#76     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
).

Error:
    #0      ModelDBImpl.fromDatastoreEntity (file:///Users/isoos/.pub-cache/hosted/pub.dartlang.org/gcloud-0.6.0+1/lib/src/db/model_db_impl.dart:130:7)
    #1      _MapStream._handleData (dart:async/stream_pipe.dart:227:21)
    #2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
    #3      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #4      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #5      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #6      _rootRunUnary (dart:async/zone.dart:1132:38)
    #7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
    #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
    #10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
    #11     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
    #12     _StreamController._add (dart:async/stream_controller.dart:640:7)
    #13     _StreamController.add (dart:async/stream_controller.dart:586:5)
    #14     List.forEach (dart:core/runtime/libgrowable_array.dart:277:8)
    #15     StreamFromPages._handlePage (package:gcloud/common.dart:61:16)
    #16     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #17     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #18     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #19     _rootRunUnary (dart:async/zone.dart:1132:38)
    #20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #21     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
    #22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
    #23     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
    #24     Future._complete (dart:async/future_impl.dart:473:7)
    #25     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
    #26     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
    #27     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
    #28     GrpcDatastoreImpl.query (package:appengine/src/grpc_api_impl/datastore_impl.dart)
    <asynchronous suspension>
    #29     Query.run.<anonymous closure> (file:///Users/isoos/.pub-cache/hosted/pub.dartlang.org/gcloud-0.6.0+1/lib/src/db/db.dart:239:12)
    #30     StreamFromPages._onListen (package:gcloud/common.dart:72:5)
    #31     _runGuarded (dart:async/stream_controller.dart:805:24)
    #32     _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:684:7)
    #33     _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:414:13)
    #34     _StreamController._subscribe (dart:async/stream_controller.dart:683:18)
    #35     _ControllerStream._createSubscription (dart:async/stream_controller.dart:818:19)
    #36     _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
    #37     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:123:10)
    #38     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:91:16)
    #39     _ForwardingStream.listen (dart:async/stream_pipe.dart:86:12)
    #40     _StreamIterator._initializeOrDone (dart:async/stream_impl.dart:1003:30)
    #41     _StreamIterator.moveNext (dart:async/stream_impl.dart:990:12)
    #42     NameTrackerUpdater._scan (package:pub_dartlang_org/frontend/name_tracker.dart)
    <asynchronous suspension>
    #43     NameTrackerUpdater.startNameTrackerUpdates (package:pub_dartlang_org/frontend/name_tracker.dart:73:15)
    <asynchronous suspension>
    #44     setupServices (file:///Users/isoos/work/google/pub/pub-dartlang-dart/app/bin/service/frontend.dart:97:40)
    <asynchronous suspension>
    #45     _main.<anonymous closure> (file:///Users/isoos/work/google/pub/pub-dartlang-dart/app/bin/service/frontend.dart:58:44)
    <asynchronous suspension>
    #46     withAppEngineServices.<anonymous closure> (package:appengine/src/appengine_internal.dart:46:51)
    #47     _withAppEngineServicesInternal.<anonymous closure> (package:appengine/src/appengine_internal.dart:115:20)
    <asynchronous suspension>
    #48     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:210:19)
    #49     _rootRun (dart:async/zone.dart:1124:13)
    #50     _CustomZone.run (dart:async/zone.dart:1021:19)
    #51     _runZoned (dart:async/zone.dart:1516:10)
    #52     runZoned (dart:async/zone.dart:1463:12)
    #53     _ServiceScope._fork (package:gcloud/service_scope.dart:209:12)
    #54     fork (package:gcloud/service_scope.dart:104:30)
    #55     _withAppEngineServicesInternal (package:appengine/src/appengine_internal.dart:105:10)
    #56     withAppEngineServices (package:appengine/src/appengine_internal.dart:46:5)
    #57     withAppEngineServices (package:appengine/appengine.dart:108:10)
    #58     _main (file:///Users/isoos/work/google/pub/pub-dartlang-dart/app/bin/service/frontend.dart:57:9)
    <asynchronous suspension>
    #59     _wrapper.<anonymous closure> (package:pub_dartlang_org/shared/service_utils.dart:225:22)
    <asynchronous suspension>
    #60     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:101:24)
    #61     _rootRun (dart:async/zone.dart:1124:13)
    #62     _CustomZone.run (dart:async/zone.dart:1021:19)
    #63     _runZoned (dart:async/zone.dart:1516:10)
    #64     runZoned (dart:async/zone.dart:1463:12)
    #65     Chain.capture (package:stack_trace/src/chain.dart:99:12)
    #66     _wrapper (package:pub_dartlang_org/shared/service_utils.dart:223:9)
    #67     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:292:17)
    #68     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by isoos** [comment]
An easy reproduction of the issue is running the `bin/tools/package_stats.dart`.

It only happens in the latest dev SDK `2.2.0-dev.0.0` (`2.1.0` is working as expected).

**Comment by jonasfj** [comment]
@isoos, is this an issue with mirrors? If so we might have to lock on 2.1, and start a process migrating away from mirrors...

**Comment by jonasfj** [comment]
We might have to check if `gcloud` package datastore wrappers works on dart 2.2, I think this uses mirrors, and it's unstable.

**Comment by isoos** [comment]
I've checked the recent dev SDKs, and `2.2.0-dev.1.1` still has the issue, while the `2.1.1-dev.0.1` is OK.

**Comment by jonasfj** [comment]
I just tested that gcloud tests pass on `2.2.0-dev.1.1`, so we probably have to find smaller test case..

**Comment by isoos** [comment]
Looks like this is related to: https://github.com/dart-lang/sdk/issues/35611
