### ISSUE TITLE
Regression of pana 0.12.7 -> 0.12.8, probably analyzer

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#1888]
pana got an analyzer upgrade just before releasig 0.12.8:
https://github.com/dart-lang/pana/pull/456

When running analysis on e.g. angular_components 0.10.0, it throws:

````
Unhandled exception:
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("package:angular/src/bootstrap/modules.template.dart")
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:228:56)
#2      LibraryContext.computeUnitElement (package:analyzer/src/dart/analysis/library_context.dart:91:26)
#3      AnalysisDriver._computeUnitElement (package:analyzer/src/dart/analysis/driver.dart:1548:34)
#4      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1145:34)
<asynchronous suspension>
#5      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2114:24)
<asynchronous suspension>
#6      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2055:5)
#7      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:77:17)
#8      new LibraryScanner (package:pana/src/library_scanner.dart:99:26)
#9      PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:266:13)
<asynchronous suspension>
#10     PackageAnalyzer.inspectPackage.<anonymous closure> (package:pana/src/package_analyzer.dart:89:22)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     withLogger (package:pana/src/logging.dart:13:61)
#16     PackageAnalyzer.inspectPackage (package:pana/src/package_analyzer.dart:75:12)
<asynchronous suspension>
#17     main (file:///Users/isoos/work/google/pub/pana/bin/pana.dart:148:34)
<asynchronous suspension>
#18     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
````

Downgrading the dependency seem to resolve the issue. I'm not yet sure if this is something we do while initializing analyzer inside pana, but we should fix it before the next release. /cc @jonasfj

**Comment by stereotype441** [comment]
@isoos I've just published analyzer version 0.34.1, which includes the fix for https://github.com/dart-lang/sdk/issues/35438.  Could you upgrade pana to this version and verify that it works?

**Comment by isoos** [comment]
@stereotype441: thanks, I can confirm that this is fixing the issue, and it also fixed a seemingly unrelated issue of https://github.com/dart-lang/pub-dartlang-dart/issues/1868.

**Comment by isoos** [comment]
Analyzer got upgraded (with pana upgrade), closing issue.
