### ISSUE TITLE
`remove_package.dart remove <pkg> <version>` is broken

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dartlang-dart#1927]
Error says `NoSuchMethodError: The method 'remove' was called on null.`

https://github.com/dart-lang/pub-dartlang-dart/blob/beab21854a8a77f5000c758c5a9a93803ac93e70/app/bin/tools/remove_package.dart#L183

Should we be doing like:
https://github.com/dart-lang/pub-dartlang-dart/blob/beab21854a8a77f5000c758c5a9a93803ac93e70/app/bin/tools/remove_package.dart#L129-L131

**Comment by jonasfj** [comment]
stack trace:
```
2019-01-09 11:25:01.551931Z Debug: Falling back to non-caching memcache implementation.
Committing changes to DB ...
Removing GCS objects ...
Unhandled exception:
NoSuchMethodError: The method 'remove' was called on null.
Receiver: null
Tried calling: remove("angular2_authentication_sample", "0.0.1-alpha.31")
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      removePackageVersion.<anonymous closure> (file:///jonasfj/projects/pub-dartlang-dart-clean/app/bin/tools/remove_package.dart:185:19)
<asynchronous suspension>
#2      DatastoreDB.withTransaction.<anonymous closure> (file:///jonasfj/.pub-cache/hosted/pub.dartlang.org/gcloud-0.6.0+1/lib/src/db/db.dart:305:32)
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#8      Future._complete (dart:async/future_impl.dart:476:7)
#9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#10     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#11     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#12     GrpcDatastoreImpl.beginTransaction (package:appengine/src/grpc_api_impl/datastore_impl.dart)
```

**Comment by isoos** [comment]
Fixed by https://github.com/dart-lang/pub-dartlang-dart/pull/1928
