### ISSUE TITLE
Cannot show page for some packages, e.g. dock_spawn

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/pub-dartlang-dart#2]
Navigating to the package page for e.g. dock_spawn on the current Dart version (https://buildbot-dart-2015-04-16-dot-dartlang-pub.appspot.com/packages/dock_spawn) returns 'Internal server error'.

The corresponding error in the log:

Error:
    The null object does not have a method 'replaceAll'.
    
    NoSuchMethodError: method not found: 'replaceAll'
    Receiver: null
    Arguments: ["\r\n", "\n"]

Stack:
    #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
    #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
    #2      markdownToHtml (package:markdown/src/html_renderer.dart:24:36)
    #3      TemplateService.renderPkgShowPage (package:pub_dartlang_org/templates.dart:140:35)
    #4      packageShowHandlerHtml.<packageShowHandlerHtml_async_body> (package:pub_dartlang_org/handlers.dart:265:57)
    #5      _rootRunUnary (dart:async/zone.dart:902)
    #6      _CustomZone.runUnary (dart:async/zone.dart:804)
    #7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
    #8      _Future._propagateToListeners (dart:async/future_impl.dart:567)
    #9      _Future._completeWithValue (dart:async/future_impl.dart:358)
    #10     Future.wait.<anonymous closure> (dart:async/future.dart:299)
    #11     _rootRunUnary (dart:async/zone.dart:902)
    #12     _CustomZone.runUnary (dart:async/zone.dart:804)
    #13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
    #14     _Future._propagateToListeners (dart:async/future_impl.dart:567)
    #15     _Future._completeWithValue (dart:async/future_impl.dart:358)
    #16     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:412)
    #17     _rootRun (dart:async/zone.dart:895)
    #18     _CustomZone.run (dart:async/zone.dart:796)
    #19     _CustomZone.runGuarded (dart:async/zone.dart:704)
    #20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:729)
    #21     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
    #22     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
    #23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
    #24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

**Comment by sgjesse** [comment]
Fixed in https://github.com/dart-lang/pub-dartlang-dart/commit/7f59e39321e3c67b6eb9414b24a19760ea12f254.
