### ISSUE TITLE
NPE in job handling

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#2175]
```
pub.job: dartdoc job error angular 5.0.0-alpha+7

Error:
   Invalid argument(s)

Stack:
   #0      _RegExp.firstMatch (dart:core/runtime/libregexp_patch.dart:192:25)
   #1      new Version.parse (package:pub_semver/src/version.dart:114:36)
   #2      DartdocBackend.removeObsolete (package:pub_dartlang_org/dartdoc/backend.dart:300:31)
   <asynchronous suspension>
   #3      DartdocJobProcessor.process (package:pub_dartlang_org/dartdoc/dartdoc_runner.dart:291:26)
   <asynchronous suspension>
   #4      JobProcessor.run (package:pub_dartlang_org/job/job.dart:55:28)
   <asynchronous suspension>
   #5      JobMaintenance.run (package:pub_dartlang_org/job/job.dart:95:18)
   #6      _workerMain.<anonymous closure> (file:///project/app/bin/service/dartdoc.dart:81:26)
   #7      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
   #8      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
   #9      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
   #10     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
   #11     _rootRunUnary (dart:async/zone.dart:1132:38)
   #12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
   #13     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
   #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
   #15     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
   #16     Future._complete (dart:async/future_impl.dart:473:7)
   #17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
   #18     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
  ```

**Comment by isoos** [comment]
It seems that the processing encountered a NPE with an entry where `entry.runtimeVersion == null`. I think it was in the first few months where we hadn't filled that field, and the publish time of the package version (Mar 7, 2018) seems to be aligned with that.

**Comment by jonasfj** [comment]
if this is a really old entity, can't we just delete it... and any files it has stored in bucket storage?
