### ISSUE TITLE
Internal server error handling /feed.atom

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/pub-dartlang-dart#23]
For some period of time on 2015-06-04 the handler for /feed.atom failed.

pub: Request handler failed

Error:
    The null object does not have a method 'replaceAll'.

```
NoSuchMethodError: method not found: 'replaceAll'
Receiver: null
Arguments: ["\r\n", "\n"]
```

```
Stack:
    #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
    #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
    #2      markdownToHtml (package:markdown/src/html_renderer.dart:24:26)
    #3      feedFromPackageVersions.<anonymous closure> (package:pub_dartlang_org/atom_feed.dart:134:19)
    #4      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
    #5      ListIterable.toList (dart:_internal/iterable.dart:219)
    #6      feedFromPackageVersions (package:pub_dartlang_org/atom_feed.dart:140:6)
    #7      atomFeedHandler.<atomFeedHandler_async_body> (package:pub_dartlang_org/handlers.dart:79:14)
    #8      _rootRunUnary (dart:async/zone.dart:902)
    #9      _CustomZone.runUnary (dart:async/zone.dart:804)
    #10     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
    #11     _Future._propagateToListeners (dart:async/future_impl.dart:577)
    #12     _Future._complete (dart:async/future_impl.dart:358)
    #13     Stream.fold.<anonymous closure> (dart:async/stream.dart:541)
    #14     _rootRun (dart:async/zone.dart:891)
    #15     _CustomZone.run (dart:async/zone.dart:796)
    #16     _CustomZone.runGuarded (dart:async/zone.dart:704)
    #17     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:390)
    #18     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399)
    #19     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:290)
    #20     _rootRun (dart:async/zone.dart:895)
    #21     _CustomZone.run (dart:async/zone.dart:796)
    #22     _CustomZone.runGuarded (dart:async/zone.dart:704)
    #23     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:390)
    #24     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399)
    #25     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:290)
    #26     _StreamController&&_SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:706)
    #27     _StreamController._closeUnchecked (dart:async/stream_controller.dart:559)
    #28     _StreamController.close (dart:async/stream_controller.dart:552)
    #29     _HttpParser._closeIncoming (dart:io/http_parser.dart:1046)
    #30     _HttpParser._doParse (dart:io/http_parser.dart:784)
    #31     _HttpParser._parse (dart:io/http_parser.dart:330)
    #32     _rootRunUnary (dart:async/zone.dart:902)
    #33     _CustomZone.runUnary (dart:async/zone.dart:804)
    #34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:712)
    #35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
    #36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
    #37     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)
    #38     _StreamController._add (dart:async/stream_controller.dart:570)
    #39     _StreamController.add (dart:async/stream_controller.dart:516)
    #40     _Socket._onData (dart:io-patch/socket_patch.dart:1793)
    #41     _rootRunUnary (dart:async/zone.dart:906)
    #42     _CustomZone.runUnary (dart:async/zone.dart:804)
    #43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:712)
    #44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
    #45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
    #46     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)
    #47     _StreamController._add (dart:async/stream_controller.dart:570)
    #48     _StreamController.add (dart:async/stream_controller.dart:516)
    #49     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1344)
    #50     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:728)
    #51     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
    #52     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
    #53     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
    #54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
```

**Comment by sethladd** [comment]
Is this still an open issue?

**Comment by mkustermann** [comment]
There haven't been any recent errors in the server logs about this AFAIK.

Though this might be caused by #7

**Comment by isoos** [comment]
The original stacktrace is very similar to the one in #2. As it was fixed, and there are no recent errors, I believe this can be closed.
