### ISSUE TITLE
Crash with invalid link

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#233]
```
Error:
    NoSuchMethodError: The getter 'url' was called on null.
    Receiver: null
    Tried calling: url

Stack:
    #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
    #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
    #2      _RelativeLinkSyntax.getLink (package:pub_dartlang_org/shared/markdown.dart:45:33)
    #3      LinkSyntax._createElement (package:markdown/src/inline_parser.dart:337:16)
    #4      LinkSyntax.createNode (package:markdown/src/inline_parser.dart:312:21)
    #5      LinkSyntax.onMatchEnd (package:markdown/src/inline_parser.dart:392:16)
    #6      TagState.close (package:markdown/src/inline_parser.dart:526:16)
    #7      TagState.tryMatch (package:markdown/src/inline_parser.dart:487:7)
    #8      InlineParser.parse (package:markdown/src/inline_parser.dart:100:23)
    #9      Document.parseInline (package:markdown/src/document.dart:40:71)
    #10     Document._parseInlineContent (package:markdown/src/document.dart:46:34)
    #11     Document._parseInlineContent (package:markdown/src/document.dart:51:9)
    #12     Document.parseLines (package:markdown/src/document.dart:35:5)
    #13     markdownToHtml (package:markdown/src/html_renderer.dart:35:32)
    #14     markdownToHtml (package:pub_dartlang_org/shared/markdown.dart:17:10)
    #15     TemplateService.renderPkgShowPage.renderFile (package:pub_dartlang_org/frontend/templates.dart:167:18)
    #16     TemplateService.renderPkgShowPage (package:pub_dartlang_org/frontend/templates.dart:190:21)
    #17     packageVersionHandlerHtml (package:pub_dartlang_org/frontend/handlers.dart:364:34)
    <asynchronous suspension>
    #18     packageShowHandlerHtml (package:pub_dartlang_org/frontend/handlers.dart:302:10)
    <asynchronous suspension>
    #19     packageHandler (package:pub_dartlang_org/frontend/handlers.dart:257:14)
    #20     appHandler (package:pub_dartlang_org/frontend/handlers.dart:60:12)
    <asynchronous suspension>
    #21     main.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///project/app/bin/service/frontend.dart:50:32)
    <asynchronous suspension>
    #22     handleRequest (package:shelf/shelf_io.dart:78:29)
    <asynchronous suspension>
    #23     main.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///project/app/bin/service/frontend.dart:44:22)
    #24     withCorrectDatastore (package:pub_dartlang_org/shared/service_utils.dart:39:15)
    #25     main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///project/app/bin/service/frontend.dart:35:16)
    <asynchronous suspension>
    #26     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:65:12)
    #27     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:58:16)
    #28     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:207:19)
    #29     _rootRun (dart:async/zone.dart:1120)
    #30     _CustomZone.run (dart:async/zone.dart:1001)
    #31     _CustomZone.runGuarded (dart:async/zone.dart:901)
    #32     runZoned (dart:async/zone.dart:1465)
    #33     _ServiceScope._fork (package:gcloud/service_scope.dart:206:12)
    #34     fork (package:gcloud/service_scope.dart:103:30)
    #35     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:56:7)
    #36     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:74:16)
    #37     _rootRunUnary (dart:async/zone.dart:1128)
    #38     _CustomZone.runUnary (dart:async/zone.dart:1012)
    #39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
    #40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    #41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    #42     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
    #43     _StreamController._add (dart:async/stream_controller.dart:667)
    #44     _StreamController.add (dart:async/stream_controller.dart:613)
    #45     _HttpServer._handleRequest (dart:io/http_impl.dart:2343)
    #46     new _HttpConnection.<anonymous closure> (dart:io/http_impl.dart:2096)
    #47     _rootRunUnary (dart:async/zone.dart:1128)
    #48     _CustomZone.runUnary (dart:async/zone.dart:1012)
    #49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
    #50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    #51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    #52     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
    #53     _StreamController._add (dart:async/stream_controller.dart:667)
    #54     _StreamController.add (dart:async/stream_controller.dart:613)
    #55     _HttpParser._headersEnd (dart:io/http_parser.dart:372)
    #56     _HttpParser._doParse (dart:io/http_parser.dart:695)
    #57     _HttpParser._parse (dart:io/http_parser.dart:318)
    #58     _HttpParser._onData (dart:io/http_parser.dart:804)
    #59     _rootRunUnary (dart:async/zone.dart:1128)
    #60     _CustomZone.runUnary (dart:async/zone.dart:1012)
    #61     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
    #62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    #63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    #64     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
    #65     _StreamController._add (dart:async/stream_controller.dart:667)
    #66     _StreamController.add (dart:async/stream_controller.dart:613)
    #67     _Socket._onData (dart:io-patch/socket_patch.dart:1643)
    #68     _rootRunUnary (dart:async/zone.dart:1132)
    #69     _CustomZone.runUnary (dart:async/zone.dart:1012)
    #70     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
    #71     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    #72     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    #73     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
    #74     _StreamController._add (dart:async/stream_controller.dart:667)
    #75     _StreamController.add (dart:async/stream_controller.dart:613)
    #76     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1228)
    #77     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
    #78     _microtaskLoop (dart:async/schedule_microtask.dart:41)
    #79     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
    #80     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
    #81     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
    "      
    severity:  "ERROR"      
```

**Comment by isoos** [comment]
Is there a specific package that crashes with it?

**Comment by isoos** [comment]
Btw. this is probably not the example code, but rather the markdown inline syntax that uses the homepage to rebase the relative links to absolutes.
