### ISSUE TITLE
w_transport package page: 500 Internal Server Error

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/pub-dartlang-dart#251]
Since about last Thursday, the w_transport package page has been failing to load:

https://pub.dartlang.org/packages/w_transport

**Comment by kevmoo** [comment]
```
pub: Request handler failed

Error:
    FormatException: Invalid character (at character 31)
    /Workiva/w_transport/README.md#request--response-interception
                                  ^
Stack:
    #0      _Uri._fail (dart:core/uri.dart:1597)
    #1      _Uri._normalize (dart:core/uri.dart:2292)
    #2      _Uri._normalizeOrSubstring (dart:core/uri.dart:2248)
    #3      _Uri._makePath (dart:core/uri.dart:2096)
    #4      new _Uri (dart:core/uri.dart:1497)
    #5      _RelativeLinkSyntax.getLink (package:pub_dartlang_org/shared/markdown.dart:46:30)
    #6      LinkSyntax._createElement (package:markdown/src/inline_parser.dart:337:16)
    #7      LinkSyntax.createNode (package:markdown/src/inline_parser.dart:330:14)
    #8      LinkSyntax.onMatchEnd (package:markdown/src/inline_parser.dart:392:16)
    #9      TagState.close (package:markdown/src/inline_parser.dart:526:16)
    #10     TagState.tryMatch (package:markdown/src/inline_parser.dart:487:7)
    #11     InlineParser.parse (package:markdown/src/inline_parser.dart:100:23)
    #12     Document.parseInline (package:markdown/src/document.dart:40:71)
    #13     Document._parseInlineContent (package:markdown/src/document.dart:46:34)
    #14     Document._parseInlineContent (package:markdown/src/document.dart:51:9)
    #15     Document._parseInlineContent (package:markdown/src/document.dart:51:9)
    #16     Document._parseInlineContent (package:markdown/src/document.dart:51:9)
    #17     Document.parseLines (package:markdown/src/document.dart:35:5)
    #18     markdownToHtml (package:markdown/src/html_renderer.dart:35:32)
    #19     markdownToHtml (package:pub_dartlang_org/shared/markdown.dart:17:10)
    #20     TemplateService.renderPkgShowPage.renderFile (package:pub_dartlang_org/frontend/templates.dart:167:18)
```

**Comment by isoos** [comment]
Ah, okay, related but not exactly the NPE that was there before.
