### ISSUE TITLE
Search queries containing 'server' (and sometimes substrings) result in 'Internal Server Error' response

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/pub-dartlang-dart#269]
Internal server error:
- https://pub.dartlang.org/search?q=server
- https://pub.dartlang.org/search?q=language+server

Looks like some substrings cause it, too... Internal server error:
- https://pub.dartlang.org/search?q=serve
- https://pub.dartlang.org/search?q=serv

But not always. No internal server error:
- https://pub.dartlang.org/search?q=language+serve

**Comment by kevmoo** [comment]
FYI @isoos

**Comment by kevmoo** [comment]
```
pub: Request handler failed

Error:
    NoSuchMethodError: The getter 'packageKey' was called on null.
    Receiver: null
    Tried calling: packageKey

Stack:
    #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
    #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
    #2      TemplateService.renderSearchPage (package:pub_dartlang_org/frontend/templates.dart:441:36)
    #3      searchHandler (package:pub_dartlang_org/frontend/handlers.dart:177:42)
    &lt;asynchronous suspension&gt;
    #4      appHandler (package:pub_dartlang_org/frontend/handlers.dart:63:19)
    &lt;asynchronous suspension&gt;
    #5      main.&lt;anonymous closure&gt;.&lt;anonymous closure&gt;.&lt;anonymous closure&gt;.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///project/app/bin/service/frontend.dart:52:32)
    &lt;asynchronous suspension&gt;
    #6      handleRequest (package:shelf/shelf_io.dart:78:29)
    &lt;asynchronous suspension&gt;
    #7      main.&lt;anonymous closure&gt;.&lt;anonymous closure&gt;.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///project/app/bin/service/frontend.dart:46:22)
    #8      withCorrectDatastore (package:pub_dartlang_org/shared/service_utils.dart:39:15)
    #9      main.&lt;anonymous closure&gt;.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///project/app/bin/service/frontend.dart:37:16)
    &lt;asynchronous suspension&gt;
    #10     runAppEngine.&lt;anonymous closure&gt; (package:appengine/appengine.dart:65:12)
    #11     runAppEngine.&lt;anonymous closure&gt;.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (package:appengine/src/appengine_internal.dart:59:16)
    #12     _ServiceScope._fork.&lt;anonymous closure&gt; (package:gcloud/service_scope.dart:207:19)
    #13     _rootRun (dart:async/zone.dart:1120)
    #14     _CustomZone.run (dart:async/zone.dart:1001)
    #15     _CustomZone.runGuarded (dart:async/zone.dart:901)
    #16     runZoned (dart:async/zone.dart:1465)
    #17     _ServiceScope._fork (package:gcloud/service_scope.dart:206:12)
    #18     fork (package:gcloud/service_scope.dart:103:30)
    #19     runAppEngine.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (package:appengine/src/appengine_internal.dart:57:7)
    #20     AppEngineHttpServer.run.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (package:appengine/src/server/server.dart:78:16)
    #21     _rootRunUnary (dart:async/zone.dart:1128)
    #22     _CustomZone.runUnary (dart:async/zone.dart:1012)
    #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
    #24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    #25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    #26     _StreamController&amp;&amp;_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
    #27     _StreamController._add (dart:async/stream_controller.dart:667)
    #28     _StreamController.add (dart:async/stream_controller.dart:613)
    #29     _HttpServer._handleRequest (dart:io/http_impl.dart:2343)
    #30     new _HttpConnection.&lt;anonymous closure&gt; (dart:io/http_impl.dart:2096)
    #31     _rootRunUnary (dart:async/zone.dart:1128)
    #32     _CustomZone.runUnary (dart:async/zone.dart:1012)
    #33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
    #34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    #35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    #36     _StreamController&amp;&amp;_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
    #37     _StreamController._add (dart:async/stream_controller.dart:667)
    #38     _StreamController.add (dart:async/stream_controller.dart:613)
    #39     _HttpParser._headersEnd (dart:io/http_parser.dart:372)
    #40     _HttpParser._doParse (dart:io/http_parser.dart:695)
    #41     _HttpParser._parse (dart:io/http_parser.dart:318)
    #42     _HttpParser._onData (dart:io/http_parser.dart:804)
    #43     _rootRunUnary (dart:async/zone.dart:1128)
    #44     _CustomZone.runUnary (dart:async/zone.dart:1012)
    #45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
    #46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    #47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    #48     _StreamController&amp;&amp;_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
    #49     _StreamController._add (dart:async/stream_controller.dart:667)
    #50     _StreamController.add (dart:async/stream_controller.dart:613)
    #51     _Socket._onData (dart:io-patch/socket_patch.dart:1643)
    #52     _rootRunUnary (dart:async/zone.dart:1132)
    #53     _CustomZone.runUnary (dart:async/zone.dart:1012)
    #54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
    #55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    #56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    #57     _StreamController&amp;&amp;_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
    #58     _StreamController._add (dart:async/stream_controller.dart:667)
    #59     _StreamController.add (dart:async/stream_controller.dart:613)
    #60     new _RawSocket.&lt;anonymous closure&gt; (dart:io-patch/socket_patch.dart:1228)
    #61     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
    #62     _microtaskLoop (dart:async/schedule_microtask.dart:41)
    #63     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
    #64     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
    #65     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
  
```

**Comment by kevmoo** [comment]
Thanks, @greglittlefield-wf - deployed the fix https://pub.dartlang.org/search?q=fooserverbar

**Comment by isoos** [comment]
@kevmoo: What do you get with the new logging? Do we have a Package entry in datastore that is missing a PackageVersion for stable but not dev?

**Comment by isoos** [comment]
I've found one culprit, an excerpt from the `language+server` query:
```
{
      "url": "https://pub.dartlang.org/packages/mist_server",
      "package": "mist_server",
      "version": "0.02.0",
      "devVersion": "0.2.0",
      "score": 22.380097377349614
    },
```

Note that the `version` is `0.02.0`, and not `0.2.0`. Direct url requests:
- works: https://pub.dartlang.org/packages/mist_server/versions/0.02.0
- 404: https://pub.dartlang.org/packages/mist_server/versions/0.2.0

The entity's fields in Datastore (staging) are:
- `version`: `0.02.0`
- `id`: `0.2.0`

The parent `Package` (in staging) has: `latestVersion = 0.2.0`.

I'm not entirely sure why the `/versions/0.02.0` works, or how it finds the `0.2.0` when accessing the package main page, but at least it is clear that:
- `PackageVersion.version` is not always the same as its key's `id`.
- The search index is built on the former, which may cause issues when we do lookup in Datastore.

**Comment by isoos** [comment]
FYI: the `analyzer` service is not affected by this, it gets the right version id and stores the `Analysis` objects with those ids.
