### ISSUE TITLE
Analyzer: Error Could not create LibraryScanner

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#284]
```
pana: Could not create LibraryScanner

Error:
    Bad state: An error occurred getting the package map for the file at `/tmp/panaoiyvGz/hosted/pub.dartlang.org/android_app_info-0.0.1/.packages`.

Stack:
    #0      new LibraryScanner (package:pana/src/library_analyzer.dart:60:7)
    #1      PackageAnalyzer.inspectPackage (package:pana/pana.dart:147:30)
    &lt;asynchronous suspension&gt;
    #2      PanaRunner.runTask (package:pub_dartlang_org/analyzer/pana_runner.dart:40:32)
    &lt;asynchronous suspension&gt;
    #3      TaskScheduler.run (package:pub_dartlang_org/shared/task_scheduler.dart:44:25)
    &lt;asynchronous suspension&gt;
    #4      _runScheduler.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///project/app/bin/service/analyzer.dart:85:10)
    &lt;asynchronous suspension&gt;
    #5      withCorrectDatastore (package:pub_dartlang_org/shared/service_utils.dart:39:15)
    #6      _runScheduler.&lt;anonymous closure&gt; (file:///project/app/bin/service/analyzer.dart:77:11)
    &lt;asynchronous suspension&gt;
    #7      withAppEngineServices.&lt;anonymous closure&gt; (package:appengine/src/appengine_internal.dart:43:51)
    #8      _withAppEngineServicesInternal.&lt;anonymous closure&gt; (package:appengine/src/appengine_internal.dart:112:20)
    &lt;asynchronous suspension&gt;
    #9      _ServiceScope._fork.&lt;anonymous closure&gt; (package:gcloud/service_scope.dart:207:19)
    #10     _rootRun (dart:async/zone.dart:1120)
    #11     _CustomZone.run (dart:async/zone.dart:1001)
    #12     runZoned (dart:async/zone.dart:1467)
    #13     _ServiceScope._fork (package:gcloud/service_scope.dart:206:12)
    #14     fork (package:gcloud/service_scope.dart:103:30)
    #15     _withAppEngineServicesInternal (package:appengine/src/appengine_internal.dart:102:10)
    #16     withAppEngineServices (package:appengine/src/appengine_internal.dart:43:5)
    #17     withAppEngineServices (package:appengine/appengine.dart:108:10)
    #18     _runScheduler (file:///project/app/bin/service/analyzer.dart:76:3)
    #19     _startIsolate.&lt;anonymous closure&gt; (dart:isolate-patch/isolate_patch.dart:268)
    #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by isoos** [comment]
This is now fixed in `pana` `HEAD`. I'm not sure which change did the fix, maybe [this](https://github.com/dart-lang/pana/issues/47).

**Comment by kevmoo** [comment]
Can close this, right?
