### ISSUE TITLE
Error 'Internal server error' for /packages/ request

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/pub-dartlang-dart#6]
The following is logged in the App Engine log:

Error:
    ApplicationError: Bad request: The key path element name is the empty string.

Stack:
    #0      catchAndReThrowDatastoreException.<anonymous closure> (package:appengine/src/api_impl/raw_datastore_v3_impl.dart:48:5)
    #1      _rootRunBinary (dart:async/zone.dart:914)
    #2      _CustomZone.runBinary (dart:async/zone.dart:812)
    #3      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:511)
    #4      _Future._propagateToListeners (dart:async/future_impl.dart:570)
    #5      _Future._complete (dart:async/future_impl.dart:348)
    #6      Stream.fold.<anonymous closure> (dart:async/stream.dart:541)
    #7      _rootRun (dart:async/zone.dart:891)
    #8      _CustomZone.run (dart:async/zone.dart:796)
    #9      _CustomZone.runGuarded (dart:async/zone.dart:704)
    #10     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:390)
    #11     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399)
    #12     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:290)
    #13     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:112)
    #14     _handleDone (dart:async/stream_pipe.dart:180)
    #15     _rootRun (dart:async/zone.dart:891)
    #16     _CustomZone.run (dart:async/zone.dart:796)
    #17     _CustomZone.runGuarded (dart:async/zone.dart:704)
    #18     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:390)
    #19     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399)
    #20     _DelayedDone.perform (dart:async/stream_impl.dart:614)
    #21     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:711)
    #22     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:671)
    #23     _rootRun (dart:async/zone.dart:891)
    #24     _CustomZone.run (dart:async/zone.dart:796)
    #25     _CustomZone.runGuarded (dart:async/zone.dart:704)
    #26     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:729)
    #27     _rootRun (dart:async/zone.dart:895)
    #28     _CustomZone.run (dart:async/zone.dart:796)
    #29     _CustomZone.runGuarded (dart:async/zone.dart:704)
    #30     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:729)
    #31     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
    #32     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
    #33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
    #34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

**Comment by sgjesse** [comment]
Fixed in 63660ec7a3ba3b0965c3815558aead5216698a0a.
