### ISSUE TITLE
Searching for "-" causes an error

### ISSUE THREAD

**Issue by natebosch** [dart-lang/pub-dartlang-dart#988]
Fatal package site error
Please open an issue: https://github.com/dart-lang/pub-dartlang-dart/issues/new

Add these details to help us fix the issue:
Requested URL - https://pub.dartlang.org/packages?q=-
   Request ID - 355e61d43838eb6ba0d993410fdb7fd9

**Comment by isoos** [comment]
Frontend got http 500 from `search`:

```
Error:
    Exception: Service returned status code 500
Stack:
    #0      SearchClient.search (package:pub_dartlang_org/shared/search_client.dart:42:7)
    <asynchronous suspension>
```

Search had a NPE:

```
pub.search: Request handler failed

Error:
    NoSuchMethodError: The getter 'iterator' was called on null.
    Receiver: null
    Tried calling: iterator

Stack:
    #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
    #1      Maps._fillMapWithMappedIterable (dart:collection/maps.dart:348)
    #2      new LinkedHashMap.fromIterable (dart:collection/linked_hash_map.dart:115)
    #3      Score.multiply (package:pub_dartlang_org/search/index_simple.dart:384:26)
```
